services:
  - type: web
    name: observatorio-cohesion-europea
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 8050
